package file

import (
	"testing"

	"github.com/stretchr/testify/assert"
)

func TestGeneratedFilesAreRecognisedByTheirHeader(t *testing.T) {
	generated := []string{
		"\xef\xbb\xbf//----------------------\n// <auto-generated>\n//     Generated using the NSwag toolchain\n// </auto-generated>\n",
		"// Code generated by protoc-gen-go. DO NOT EDIT.\n\npackage x\n",
		"# Generated by Django 3.2.4 on 2021-06-11 09:00\n\nfrom django.db import migrations\n",
	}
	for _, src := range generated {
		assert.Truef(t, IsGenerated([]byte(src)), "%q", src)
	}
	handWritten := []string{
		// Broadleaf's JPA entities.
		"@Entity\npublic class EmailTrackingImpl {\n  @Id\n  @GeneratedValue(generator = \"EmailTrackingId\")\n",
		"// This comment says Code generated by hand, and nothing else.\n",
		"",
	}
	for _, src := range handWritten {
		assert.Falsef(t, IsGenerated([]byte(src)), "%q", src)
	}
}
