package file

import (
	"bytes"
	"regexp"
)

const (
	// One per file that is someone else's code carried in the repository.
	ThirdPartyFileCount = "complexity__files__third_party"
	// One per file a tool wrote and says so in its header.
	GeneratedFileCount = "complexity__files__generated"
)

// IsGenerated reports whether a file's header says a tool wrote it.
//
// nopCommerce's UPS plugin carries an NSwag client of 6,021 lines that
// declares 140 things; it was the codebase's most crowded module and one of
// its unhealthiest files, and no one there wrote a line of it. Generated code
// is still part of the build -- other code imports it, so it keeps its units
// and its edges -- but a health reading or a "split this up" says nothing
// about a file nobody edits by hand.
//
// Only the markers tools write verbatim count. A loose "@generated" matched
// Broadleaf's @GeneratedValue on hand-written JPA entities.
func IsGenerated(content []byte) bool {
	head := content
	if len(head) > 2048 {
		head = head[:2048]
	}
	return generatedMarker.Match(head) || bytes.Contains(head, []byte("<auto-generated"))
}

var generatedMarker = regexp.MustCompile(`(?m)` +
	// Go's convention, https://go.dev/s/generatedcode
	`^// Code generated .* DO NOT EDIT\.$|` +
	`Generated by the protocol buffer compiler\.\s+DO NOT EDIT|` +
	// Django migrations: "# Generated by Django 4.2 on 2023-05-01 10:00"
	`^# Generated by Django \d`)
