package stats

// Stats are a map of stat type to value
// For example: {"function": 10, "class": 5}
// These stats are usually the number of Snippet of a certain type
// Stats can also be generated by a StatProvider
type Stats map[string]interface{}

// StatsGroup is a mapping of a name to a Stats
type StatsGroup map[string]*Stats
type Record struct {
	StatType string
	Value    interface{}
}

func (s StatsGroup) SetStat(key, stat string, value interface{}) {
	if _, has := s[key]; !has {
		s[key] = &Stats{}
	}
	(*s[key])[stat] = value
}
