package analysis

// Stats are a map of type to count
// For example: {"function": 10, "class": 5}
// These counts are usually the number of Snippet of a certain type
// Stats can also be generated by a StatProvider
type Stats map[string]int

// StatsGroup is a mapping of a name to a Stats
type StatsGroup map[string]*Stats

// A StatProvider is an interface that can generate Stats for a particular File
type StatProvider interface {
	GetStatsFromFile(file File) *Stats
}

// MergeMultipleStats into one.
func MergeMultipleStats(statsToMerge []*Stats) *Stats {
	statsToReturn := make(Stats)

	for _, stats := range statsToMerge {
		for key, value := range *stats {
			statsToReturn[key] += value
		}
	}
	return &statsToReturn
}

func snippetsToStats(snippets []*Snippet) *Stats {
	stats := make(Stats)
	for _, snippet := range snippets {
		stats[snippet.Type]++
	}
	return &stats
}
