package analysis

import "github.com/samber/lo"

// Stats are a map of type to count
// For example: {"function": 10, "class": 5}
// These counts are usually the number of Snippet of a certain type
// Stats can also be generated by a StatProvider
type Stats map[string]int

// StatsGroup is a mapping of a name to a Stats
type StatsGroup map[string]*Stats

// MergeMultipleStats into one.
func MergeMultipleStats(statsToMerge []*Stats) *Stats {
	statsToReturn := make(Stats)

	nonNilStats := lo.Filter(statsToMerge, func(stats *Stats, _ int) bool {
		return stats != nil
	})
	for _, stats := range nonNilStats {

		for key, value := range *stats {
			statsToReturn[key] += value
		}
	}
	return &statsToReturn
}

func SnippetsToStats(snippets []*Snippet) *Stats {
	stats := make(Stats)
	for _, snippet := range snippets {
		stats[snippet.Type]++
	}
	return &stats
}
